### ISSUE TITLE
train every epochs

### ISSUE THREAD

**Issue by AlonDan** [iperov/DeepFaceLab#134]
Sorry I wasn't sure where to post the idea.

When running "train H64.bat" for example (or any other train) on the setup/questions.
Is it possible to add:
SAVE EVERY (number here) Epochs?

So instead of pressing [s] manually, can we make it save automatically every X epochs?

Same for preview, instead of pressing [p] manually, Preview automatically every X epochs?

This could be very useful, I hope it is not too hard to add, if it is sorry it's just a suggestion that may be helpful to all of us.

Keep up the good job! :)

**Comment by iperov** [comment]
it is already saving every 10 minutes, it is better than epochs.

**Comment by AlonDan** [comment]
Oh thanks for the quick reply, I appreciate it!
And I didn't know it is limited to just 10 minutes, I'm still experimenting

I thought it will be much more dynamic, since my machine won't let it hold more than 4-8 minutes and it's out of memory, I would like to save it more often, instead of using 4-8 batch-size.

Will it reduce the quality if I'll reduce the batch to 1-2 ?
because it is out of memory all the time, I tried 4 different projects to make sure it is not something about the specific project.

Here is my latest status for example, maybe I do something wrong:

===== Model summary =====
== Model name: H64
==
== Current epoch: 10006
==
== Model options:
== |== batch_size : 8
== |== sort_by_yaw : False
== |== random_flip : True
== |== lighter_ae : False
== |== target_epoch : 100000
== Running on:
== |== [0 : GeForce GTX 980]


I know that my specs are extremely low for the above settings, but 4-8 minutes and saving every X minutes without able to change it like epochs is not useful:

CPU: i7 4770k  |  32GB Ram  |   GeForce GTX 980 4GB   |  SSD 480GB

For now I just try to make it work without going out of memory.  anyway thanks for the reply I'll try to ask somebody how to make it work or something since I'm new to this.

**Comment by iperov** [comment]
sorry I will not add functionality sacrificing simplicity to help < 20% of users.

**Comment by AlonDan** [comment]
Thanks for the reply, no problem I appreciate all you do for this!

I just found out about another software called FakeApp I will use this for now since I found out these features are there, not sure if you responsible for this or not but it looks good, also nice GUI.

Sorry if this is an old thing or something, I'm new to this and experimenting before making a simple GUI for the .bat files for more user-friendly.

Keep up the good job and have a nice day! :)

**Comment by iperov** [comment]
FakeApp is outdated.
Good luck ;-)

**Comment by AlonDan** [comment]
WOW! Thanks for telling me, then I won't waste my time on it.

I'll better make the simple GUI (nothing fancy) based on the current of the .bat files of DeepFaceLab!
I'm not a programmer but making a GUI is not complex and the .bat files with the steps are very easy to follow, I appreciate you did all this! I'll try to help with my share since nobody made a GUI yet (unless I don't know about it).

**Comment by iperov** [comment]
DFL is not complex.
just watch tutorials

Basic workflow: https://www.youtube.com/watch?v=K98nTNjXkq8
Basic workflow (derpfakes): https://www.youtube.com/watch?v=cVcyghhmQSA
How To Make DeepFakes With DeepFaceLab - An Amatuer's Guide: https://www.youtube.com/watch?v=wBax7_UWXvc
Manual re-extract bad dst aligned frames: https://www.youtube.com/watch?v=7z1ykVVCHhM

**Comment by AlonDan** [comment]
Yeah I actually use it based on the tutorials which are very helpful! that's how I did my few tests but unfortunately my hardware is not enough to hold 10 minutes of save hehe.

Anyway, what I'm trying to do for the community and helping your hard work is a GUI instead of clicking the .bat files, just selecting a variation of each step using... buttons? it will just trigger the specific .bat files but looks nicer especially for newcomers.

**Comment by iperov** [comment]
if you are using windows 10, disable aero desktop

**Comment by GAN-er** [comment]
@AlonDan 
First of all, this should not be happening, but indeed it does. I mean a given batch size working fine for X epochs, and then at X+1 throwing an OOM error. 
It does not happen always, and I have not been able to pinpoint when exactly happens. 
In any case, you can change the saving time yourself. 
Go in the "_internal\bin\DeepFaceLab\mainscripts" and open Trainer.py with a text editor.
Then check line 14:
def trainerThread (input_queue, output_queue, training_data_src_dir, training_data_dst_dir, model_path, model_name, save_interval_min=10, debug=False, **in_options):

Change the save_interval_min to whatever you want. e.g. save_interval_min=5 will be saving every 5 minutes, etc. 
iperov goes for simplicity and having users needing to pick one more parameter will only need to more noob questions about it, and for something that is frankly rare. 
You can even change the save interval to be based on iterations instead of a fixed time, by doing a very minor alteration. 
However, if you do not know what I am talking about, then just leave it as it is. 
I do not want to say to people how to introduce new code and then having to deal with all the mistakes and confusion that will result from that. 

Good luck!
