### ISSUE TITLE
RuntimeError: Expected numpy.ndarray of uint8

### ISSUE THREAD

**Issue by jw2200** [iperov/DeepFaceLab#148]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

Using the new DeepFaceLabTorrent_build_15_02_2019 Windows prebuilt release, when running the batch job "5) data_dst extract faces DLIB best GPU.bat" I receive the error message below.

## Actual behavior

Error Message:

```
Running extractor.

Performing 1st pass...
Running on GeForce GTX 1080 Ti.
  0%|                                                                                         | 0/1107 [00:00<?, ?it/s]Exception while process data [D:\DeepFaceLabTorrent_build_15_02_2019\DeepFaceLabTorrent\workspace\data_dst\00001.png]: Traceback (most recent call last):
  File "D:\DeepFaceLabTorrent_build_15_02_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\utils\SubprocessorBase.py", line 243, in subprocess
    result = self.onClientProcessData (data)
  File "D:\DeepFaceLabTorrent_build_15_02_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\mainscripts\Extractor.py", line 304, in onClientProcessData
    rects = self.e.extract_from_bgr (image)
  File "D:\DeepFaceLabTorrent_build_15_02_2019\DeepFaceLabTorrent\_internal\bin\DeepFaceLab\facelib\DLIBExtractor.py", line 31, in extract_from_bgr
    detected_faces = self.dlib_cnn_face_detector(input_image, 0)
RuntimeError: Expected numpy.ndarray of uint8
```

## Steps to reproduce

Run extract jobs

## Other relevant information

Win10 x64, GTX 1080TI
Previous release (DeepFaceLabTorrent_build_07_02_2019) is working fine.

**Comment by iperov** [comment]
cannot reproduce bug. All works fine

**Comment by iperov** [comment]
post your images which you are trying to extract

**Comment by lackeyproton** [comment]
I can confirm that mine failed as well, either similar or exactly the same error. I will attempt to find which image and post. I have a GTX 1070 Ti.

**Comment by lackeyproton** [comment]
@jw2200, I tried to reproduce that error, which happened to me a couple of days ago. It turned out that the offending image was a PNG in my dst_src directory which I was extracting. Try converting all your PNGs to jpgs. Once I converted them to jpg, I no longer get the error. 

I think it might be a certain type of PNG that the code doesn't like. The PNGs from DFL's video extractor produces compatible PNGs. So yours must have been from another source? The one that was crashing from me was taken from a still camera, not from a video.
