### ISSUE TITLE
Seems impossible to raise batch size past 16 or 32

### ISSUE THREAD

**Issue by toxsickcity** [iperov/DeepFaceLab#160]
Downloaded recent 23th Feb version from mega
Tried an older version too maybe 2 weeks older.

I am using sae training method.

When try put 64 batch size it fails. It starts with 16 and 32..

I am sure I have seen other apps which do faceswap reach batch of 512 maybe up-to 1024 on a 1080i 11GB card

Is there a benefit to keeping it low? Or is there a way to increase the batch size.. 

Thanks

**Comment by iperov** [comment]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce
