### ISSUE TITLE
[Linux] Error: OOM when allocating tensor with shape

### ISSUE THREAD

**Issue by tetlie** [iperov/DeepFaceLab#187]
Similar issue: https://github.com/iperov/DeepFaceLab/issues/119

I get `Error: OOM when allocating tensor with shape` when running the train models (`6_train_H64.sh`and `6_train_128.sh`, same with the "no-preview" versions). 

@iperov suggested in the example above of using to use the lightweight encoder and a very small batch size. I've tried many different batch-sizes, with and without lightweight auto-encoder, both with the H64 and H128. I get the same issue even when running lightweight with a batch size of 2. 

IMPORTANT: I run this on the **Linux-fork** (https://github.com/lbfs/DeepFaceLab_Linux) on a **Quadro P5000 (16 GB)** on a **Linux ML-in-a-Box Paperspace** configuration.

Any idea what the problem could be?
I can't imagine that the lack of VRAM is the actual issue with his card.

<img width="1350" alt="Screenshot 2019-03-12 at 13 40 42" src="https://user-images.githubusercontent.com/31843785/54201816-e2c4a280-44ce-11e9-9f90-0aea5580882b.png">

**Comment by iperov** [comment]
cuda/cudnn driver versions may be incorrect with tf version

**Comment by lbfs** [comment]
I did find one other issue relating to OOM on another project with this card when multigpu's are installed in the system, I don't know if it's a mismatch of cuda/cudnn simply because he is using an Anaconda environment, however these machines are running Ubuntu 14.04 which I consider to be incredibly old at this point and they are loading with machine learning tools already so there could be a potential configuration issue as well.

I have not received a response in over 7 days after asking for more information on the thread he created in my repo, so I don't know if this should stay open or not since I cannot help without additional info.

**Comment by starstarly** [comment]
I have the same problem .And i wonder if anyone can help to fix this.
