### ISSUE TITLE
Video synthesis frame skipping problem

### ISSUE THREAD

**Issue by sktbest** [iperov/DeepFaceLab#204]
Video synthesis frame skipping problem
Synthetic video skipping frames are now common
But the original composite video does not skip frames.
Can you improve the composite video in the new version so that it is not skipping frames?
Or put the original synthetic video back in the thank you

**Comment by iperov** [comment]
## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*
