### ISSUE TITLE
Automatically using CPU for everything CPU usage is at 70% percent while GPU is at 5% while training and runs very slow. It says running on my RTX 2070. I have the latest drivers and using DeepFaceLabCUDA10.1SSE (Windows 10)

### ISSUE THREAD

**Issue by jask2000** [iperov/DeepFaceLab#211]
Automatically using CPU for everything CPU usage is at 70% percent while GPU is at 5% while training and runs very slow. It says running on my RTX 2070. I have the latest drivers and using DeepFaceLabCUDA10.1SSE (Windows 10)

**Comment by jask2000** [comment]
CPU usage is at 70% percent while GPU is at 5% while training and runs very slow. I'm using an RTX 2070.

**Comment by iperov** [comment]
## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

**Comment by jask2000** [comment]
Sorry about the stupid question I'm really an amateur. So i recently installed downloaded deepfacelab and noticed that while training or extracting faces my gpu usage doesn't go above 20% in task manager. HWMonitor shows 95 -100% usage at all times but task manager shows less than 20%. I am using an i5 9400f and an RTX 2070. My card runs fine while playing games and shows much higher usage in task manager. I have not installed cuda, cudnn or anything else on my PC except for DeepFaceLabCUDA10.1SSE and latest drivers from nvidia. I'm not sure if task manager is showing false values or if my card is not being used properly by this program.

**Comment by iperov** [comment]
why are you worrying about gpu usage ?
DFL designed to extract maximum performance from pc config. But performance measured on slowest element in a system. SO there are a lot of reasons why gpu is not at maximum usage/

**Comment by vjay99** [comment]
@iperov 
This is likely due to Nvidia placing the nvml.dll in system32 directory in the newer Windows 10 "DHC" format drivers.  The fix for this issue is already committed below in pynvml.py.  You just need to update the file from source below.

https://github.com/nicolargo/nvidia-ml-py3/commit/34218216f571aac0b4256271d3a2c168aadd2139

**Comment by iperov** [comment]
@vjay99 thx
