### ISSUE TITLE
Some questions about styleLoss

### ISSUE THREAD

**Issue by theoldgun** [iperov/DeepFaceLab#259]
Great project！
I have a few questions and hope to get an answer.

1.When doing style_loss, Gaussian blur is performed on ‘target’ and ‘style’ respectively, and what effect does Gaussian blur play.
2.How to balance the two parameters ‘Face style power’ and ‘Background style power’, whether there is a set of common parameters or better strategies to adjust on my own data.

Very very hopeful to get your reply!
Thank you~

**Comment by iperov** [comment]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce
