### ISSUE TITLE
Feature request: sharpen extracted aligned images

### ISSUE THREAD

**Issue by nkomarov** [iperov/DeepFaceLab#273]
>Src faceset must be as sharp as possible.
_Originally posted by @iperov in https://github.com/iperov/DeepFaceLab/issues/144#issuecomment-462319057_

Then in this case, I would suggest that source images would be sharpened. I tried a simple software that applies USM (unsharp mask) sharpening, it gives outstanding results. I guess you could add such an optional step. Imagemagick or something else should be able to do that.

Also, on the latest stage there is generated face that's going to be applied over an original one. Before actually merging it into the original frame, it would be great to sharpen eyes and mouth, it would significantly improve the quality. As a user, I can't sharpen this middle of the face after it's already merged into the frame, but I guess a developer can do so.

![2019-05-30_17-23-55](https://user-images.githubusercontent.com/620930/58663455-d6612080-832c-11e9-81f9-d1cc4ec15968.png) - example of USM-sharpening in FastStone Viewer Batch Convert.

**Comment by TooMuchFun** [comment]
```
face_image = cv2.GaussianBlur(face_image, [0, 0], 3)`
face_image = cv2.addWeighted(face_image, 1.5, face_image, -0.5, 0)
```

If running from script try adding this before the `cv2_imwrite`. Test and maybe it could be merge in.

**Comment by nkomarov** [comment]
Hi, thanks for your answer. Based on the method name, I suspect this code will **blur** the image, which is opposite to what I suggested (**unblur**). Another thought - this probably could be more effective if done by the GPU, by the shader. Sorry if I use the terms incorrectly, but I guess you get what I mean.

**Comment by CryptoAnarchist777** [comment]
This sounds like it would be useful but I'm curious if sharpening the alignments of the original face would be needed since it's just going to be replaced anyways (although it could be useful for training if your original video face alignments are of poor quality) I guess you could have an option to do it for each process, however I think the merge part would benefit the most.

DFL is vastly superior than previous public deepfakes programs (that I've seen) but I do notice the faces are blurred more than some other options (this is without tweaking things and just using some of the different options I have found) but overall DFL is vastly superior, this would pretty much fix any outstanding personal issues I have with it. I don't comment on here much but while I'm joining the discussion I just wanted to say thanks to iperov and any others that have contributed for all the hard work they have done up until this point and going forward.

As an aside there is a lot of ai upscaling features becoming commercially available that don't just sharpen or blur but actually intelligently render higher definitions of that image, hopefully something like this gets implemented eventually. although for something like that with tens of thousands of images per video I'm not sure what that would look like rendering time wise on a single graphics card even if it is in the mid to upper range.

**Comment by TooMuchFun** [comment]
USM is defined as a composite of the blurred and unblurred images. Per Wikipedia,

`The "unsharp" of the name derives from the fact that the technique uses a blurred, or "unsharp", negative image to create a mask of the original image.[1] The unsharped mask is then combined with the positive (original) image, creating an image that is less blurry than the original. `

The processing for sharpening is negligible and is better suited for bootstrapping when loading the samples or simply an extraction option. Please try this feature and benchmark it, thanks.

**Comment by nkomarov** [comment]
Sorry, I have weak hardware and no experience with DFL so it would be hard for me to test.

**Comment by Auroir** [comment]
This is possible now if you export your images with alpha and use FFmpeg filters.
I have a functioning setup that filters all 4 components. 5 if you want to change the audio.
1) Destination frame
2) Face
3) Mask
4) Merged frame

Something like this:
```
Face Overlays   -> Face Filters ---> [postRGB] ------
                |                                     \
                 \                                     V
                  -> Mask Filters ---> [postAlpha] -->[postOverlay] 

Original Frames -> Dest Filters ---> [postDest]

            [postOverlay][postDest] -> [merged]
            [merged] -> Merged Filters -> [vOut]

Original Audio -> Passthrough -> [aOut]
```

See:
https://trac.ffmpeg.org/wiki/FilteringGuide
https://ffmpeg.org/ffmpeg-filters.html#unsharp-1
https://ffmpeg.org/ffmpeg-filters.html#alphaextract
https://ffmpeg.org/ffmpeg-filters.html#overlay-1
