### ISSUE TITLE
Feature request: sub-option for learn mask option while training

### ISSUE THREAD

**Issue by tania010** [iperov/DeepFaceLab#279]
@iperov  i'm proposing/requesting a new option in "learn mask" training: ADDING _dst and _src masks together: https://i.imgur.com/3uKwhm0h.jpg

![Untitled 1](https://user-images.githubusercontent.com/51423213/58991767-838ed980-8802-11e9-825d-e3ae92e1cee6.jpg)

It should look at the _src mask relative to the face alignments and use that (src) mask to learn what areas to mask (on to the dst) and learn.

**Comment by tania010** [comment]
currently, the only way i can get the mole to appear on the merged face is by using following settings in convert:
Mode: (5) RAW
raw mode: (1) rgb
Mask mode: (1) learned
![00208-1](https://user-images.githubusercontent.com/51423213/59037952-b7faa800-888b-11e9-93e2-650f47b7adc7.png)

Mode: (1) overlay with mask mode: (1) learned does not help
![00208-2](https://user-images.githubusercontent.com/51423213/59038420-74546e00-888c-11e9-96c4-406f4996aff9.png)

**Comment by Auroir** [comment]
1) Stop making deepfake porn.

2) The mole does not appear in other modes because the mask doesn't cover that part of the forehead. If it was on the cheek then it would appear as long as you disabled the horizontal flipping option during training. 

If you're so inclined you could extract the face landmark locations and add in a "ie" poly to show the mole. Look into the DFLJPG module, and the mask editor to get an understanding of how the polys are defined, then do some math based on the existing landmarks, add in the mole poly. 

It won't be easy but it's very possible. If you do it please share!
