### ISSUE TITLE
Glass Frame Issue

### ISSUE THREAD

**Issue by itisyeetimetoday** [iperov/DeepFaceLab#280]
## Expected behavior

When training the fake, it appears to have learned glasses frames, but when actual result is rendered out, no side frames on the side of the head are shown.

**Comment by tania010** [comment]
I believe that you used FAN-x during convert? in the training, it will show everything in the masked area, but if you use FAN-x the glasses or any other obstruction will not be present. if you use any option other than FAN-x during convert, i think the glasses/frame will appear. So it IS an expected behavior if you are/were planning to use FAN-x.

**Comment by itisyeetimetoday** [comment]
I do not see any option to use FAN-X for the convert H-128.bat  file
