### ISSUE TITLE
The face I extract on Windows is PNG, but the face I extract on python is only JPG?

### ISSUE THREAD

**Issue by zpeiguo** [iperov/DeepFaceLab#294]
The face I extract on Windows is PNG, but the face I extract on python is only JPG?

**Comment by feepdakenoob** [comment]
Come on, more information. Is this a bug or a question? Try harder.

**Comment by zpeiguo** [comment]
> 来吧，更多的信息。这是窃听器还是问题？再加把劲。

Sorry, I don't know anything about it.What format did you extract?My extracted faces are all .JPG, I feel the training effect is very poor.

**Comment by Auroir** [comment]
You are correct. There are a couple of issues at play here in my option, but the easiest fix is to edit this line.
https://github.com/iperov/DeepFaceLab/blob/master/mainscripts/Extractor.py#L252
`[int(cv2.IMWRITE_JPEG_QUALITY), 85]`
to
`[int(cv2.IMWRITE_JPEG_QUALITY), 100]`

Just find "Extractor.py", open it with a text-editor, and change the value. At least the JPGs will be full quality.

**Comment by zpeiguo** [comment]
> You are correct. There are a couple of issues at play here in my opinion, but the easiest fix is to edit this line.
> https://github.com/iperov/DeepFaceLab/blob/master/mainscripts/Extractor.py#L252
> `[int(cv2.IMWRITE_JPEG_QUALITY), 85]`
> to
> `[int(cv2.IMWRITE_JPEG_QUALITY), 100]`
> 
> Just find "Extractor.py", open it with a text-editor, and change the value. At least the JPGs will be full quality.

Thank you for your answer.I found that only the old version is PNG, now the latest version is JPG.I don't understand the code.But it's well known that PNG's size resolution is significantly better than JPG's, so I don't see why the authors would want to drop the format.

**Comment by Auroir** [comment]
I noticed this a while ago as well. DFLPNG is there and works great, but it's just not used. I patched my repo to use it if you want to take a look at the differences. It's only a few lines to change, all the methods are named the same between DFLJPG and DFLPNG.

My hope is that something else breaks with PNGs and that's why it's not enabled, else I'm not sure why they would purposefully sandbag their own project. Having lossless src faces unlocks a lot of possibilities like altering your src faces to match the dst face hue, or sharpening/blurring post-extraction. Right now as a JPG any alterations further reduces quality.
