### ISSUE TITLE
Training Error H64

### ISSUE THREAD

**Issue by GamingLucas** [iperov/DeepFaceLab#307]
## Expected behavior

I'm trying to Train, but everytime I run the batch file I get this error code.
<img width="787" alt="deepfacelog" src="https://user-images.githubusercontent.com/43099632/61175003-7fe03680-a5a8-11e9-9c61-59d7f1ff7e2b.png">

**Comment by sdgandhi** [comment]
Unfortunately you're running out of memory. Keep track of your memory using Task Manager to see if it's a RAM or video memory issue. H64 theoretically should be good to use on weaker GPUs, but maybe not for yours.

**Comment by Auroir** [comment]
This is not a memory issue, it looks like the training starts but then fails at iteration 836.

OP, why are you running OpenCL on a Nvidia GPU? Does the 960 not support a version of CUDA that works with DFL? The OpenCL version _should_ work since it's is an open spec that nvidia supports, but try a CUDA version of deepfacelab anyway.

Besides that, seeing the plaidml log lines more than one (at startup) is a bad sign. Make sure your system is otherwise idle when training your model.

**Comment by Scafidel** [comment]
I've had this error, too.  I had to delete the files in the model and try again.  Try that...
