### ISSUE TITLE
Bottom part of the mask creating a nasty edge

### ISSUE THREAD

**Issue by jejz** [iperov/DeepFaceLab#320]
![image](https://user-images.githubusercontent.com/19254175/62144350-ef1c9100-b2f1-11e9-99f2-8cc75e299416.png)

this is the problem. when the chin part of the mask is too close, it will spill over the edge of the frame and creates this nasty edge.

but there is already a fix for this in DFL, just in a different place.

![image](https://user-images.githubusercontent.com/19254175/62144885-d496e780-b2f2-11e9-8e63-320e64b026ab.png)
this is the convert debug. first step. the stock mask. as you can see, it sits on the right edge of the frame. if i blurred the mask as is, the gradient would spill over the edge and crated that nasty line. 

but theres already a fix for that:

![image](https://user-images.githubusercontent.com/19254175/62144513-43277580-b2f2-11e9-918b-e5f5d92286c6.png)
during the erode step (example above is erode = 0) the mask is capped by a gradient moving it further from the edge. so after the blurring parts, its in bounds of the frame.

![image](https://user-images.githubusercontent.com/19254175/62144628-7bc74f00-b2f2-11e9-98c3-7c6197d18ecc.png)
as you can see thers no spill on the side, but there is a spill bellow the chin, which creates that edge line. 

![image](https://user-images.githubusercontent.com/19254175/62144717-98638700-b2f2-11e9-9d54-6dd14f54494d.png)
heres a demonstration of that. if tha mask is too close to the edge, it spills behind the edge.

so if the same step as on the right or left side of the frame was copied to the bottom and maybe iven to the top, it would be fixed. no more ugly lines.

iperov if you can do a simple quick fix for this ill donate more money again.. it would help a lot because this is the problem i have with every single project, the edge line under the chin.
or if anyone else could find the side edge gradient and aplly it to all sides of the frame, most importantly to tho bottom edge that would be awesome too.

**Comment by iperov** [comment]
send workspace with one problem frame in dst\ to my email

**Comment by jejz** [comment]
you got it.

**Comment by ytn2001** [comment]
![image](https://user-images.githubusercontent.com/36368758/62624963-dbf36c00-b956-11e9-91f0-ab6a141a162b.png)
![image](https://user-images.githubusercontent.com/36368758/62624987-e9a8f180-b956-11e9-8617-7cafeda0a758.png)
**Will increase the clipping range**
![image](https://user-images.githubusercontent.com/36368758/62626365-cf244780-b959-11e9-8ee3-ed39c5c8ef78.png)
**RE-Extractor  and  RE-Trainer**
![image](https://user-images.githubusercontent.com/36368758/62625592-1b6e8800-b958-11e9-965e-25bf68e1496b.png)
----------------------------------------------------------------------
PS: However, the face area thus extracted will be 75% of the original. I try to increase the position of the extracted face and expose the neck part so that the original area can be maintained, but I don't know how to modify it.

**Comment by ZakariaMHTX** [comment]
I got the same problem. could someone help me to solve it.
https://i.redd.it/nv1fafm2q1f31.png

**Comment by limiday** [comment]
> send workspace with one problem frame in dst\ to my email

what about you email?

**Comment by limiday** [comment]
> send workspace with one problem frame in dst\ to my email

@iperov what about you email?
