### ISSUE TITLE
 What is good and efficient ??

### ISSUE THREAD

**Issue by dok2zino** [iperov/DeepFaceLab#329]
I am using gtx1080ti and 32gb ram

Which is best to use h64, df or sae?

Please let me know that the quality comes out most efficiently

**Comment by Auroir** [comment]
Use SAE.

I use a 1080 8gb on Win10. Remember on Win10 you can only use about 85% of your vram, if you want to use all of it you need to dualboot into something else. So I'm using about 7GB of vram with these models. Also I prefer LIAE simply because I've had better luck with it, feel free to explore your options.

My favorites:
**SAE-LIAE 176px, Full face @ 200/40/20**
I run this with a 10 batch size (you can up the batch size when style is set to 0) but you should be able to do a few higher. This is a slower one since batch size is under 16, but it's not terribly slow like something with bs of 6.
**SAE-LIAE 192px, Full face @ 192/32/14**
I liked this one for a while but the decoder with only 14 dimensions didn't work out well on some faces. I ended up replacing this with the 176px one above.
**SAE-DF 256px, Full face @ 400/38/19**
This is the biggest model you'll want to run. I think it was batch size 4 for me, you might get 6 out of it with optimizer mode 3. It's going to take a week to finish, but if you really want 256x256 output, this is the one. 
**SAE-LIAE 128px, Full face @ 222/34/16**
Tiny model. Makes quick ones at a batch size of ~24, but only 128x128px output. If you are willing to resize your destination to 720p or lower this works surprisingly well. Especially if you export with alpha and do some light post-processing. 

It's important to remember that the iterations required to get a good results increases as batch size decreases. With batch size of 6 I shoot for 150k iters. With 12 the goal is 100k iters, and 24 gets 50k. Do not train with a batch size above 32, it becomes too generalized and your results will suffer for it.

**Comment by unknownentity123** [comment]
@Auroir What are the parameters represented by the X/Y/Z to the right of the @ symbol in your descriptions? Thanks for the recommended settings BTW.

I'm guessing those are ae_dims , e_ch_dims, and d_ch_dims in that respective order. What optimizer mode are you using for each of those, do you turn on Face or Background style?
What do you set the newer settings like apply_random_ct and clipgrad to?

**Comment by Auroir** [comment]
Those are the dimensions, yes. The rest is up to your system specs and your project. Try things out.

**Comment by Auroir** [comment]
If you don't know how to tune the model size to fill your GPU, I wrote steps in another issue. My suggestions here are just things that worked for me, the best models will always be the ones you tune to your specific machine.
See #334

**Comment by bkapvt** [comment]
what is Clipgrad? 

btw loving all your advice, you're the hero we need!
