### ISSUE TITLE
Manual extract error

### ISSUE THREAD

**Issue by Tesla32X** [iperov/DeepFaceLab#395]
THIS IS NOT TECH SUPPORT FOR NEWBIE FAKERS
POST ONLY ISSUES RELATED TO BUGS OR CODE

## Expected behavior
*Doing manual extracts*

## Actual behavior

*Suddenly the manuel extracts stops and the software throws and error. All work on previous frames is lost.*

## Steps to reproduce

*Start manual extract, annotate a few frames and see if the software jumps out.*

## Other relevant information

Performing manual extract...
Running on GeForce GTX 1080 Ti.
Using TensorFlow backend.
 16%|######                                | 36/219 [23:38<2:00:08, 39.39s/it]T
raceback (most recent call last):
  File "\Downloads\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\ma
in.py", line 250, in <module>
    arguments.func(arguments)
  File "\Downloads\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\ma
in.py", line 35, in process_extract
    'multi_gpu' : arguments.multi_gpu,
  File "\Downloads\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\ma
inscripts\Extractor.py", line 858, in main
    data = ExtractSubprocessor ([ ExtractSubprocessor.Data(filename) for filenam
e in input_path_image_paths ], 'landmarks', image_size, face_type, debug_dir, cp
u_only=cpu_only, manual=True, manual_window_size=manual_window_size).run()
  File "\Downloads\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\jo
blib\SubprocessorBase.py", line 222, in run
    self.on_result (cli.host_dict, obj['data'], obj['result'])
  File "\Downloads\DeepFaceLabCUDA10.1AVX\_internal\DeepFaceLab\ma
inscripts\Extractor.py", line 558, in on_result
    view_landmarks  = (np.array(self.landmarks) * self.view_scale).astype(np.int
).tolist()
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
Press any key to continue . . .

- **Operating system and version:** Windows

**Comment by iperov** [comment]
I cannot reproduce.
Can you send your images?

**Comment by iperov** [comment]
and record your extraction process on video

**Comment by Tesla32X** [comment]
Yes, whats your email again? This seems to happens on the same frame, so apparantly there is something wrong with it. Will try to do a recording later today.

**Comment by iperov** [comment]
deepfakescovery@gmail.com

**Comment by Tesla32X** [comment]
Just passed on some pictures and a recording of the process. I got a different error this time, but bottom line is that I am not able to complete a manual extract. (I have done so in the past with zero issues.)

**Comment by iperov** [comment]
fixed

**Comment by Tesla32X** [comment]
Ah, perfect! I will download and give it a try asap.

**Comment by Tesla32X** [comment]
Allright, the black and white error is gone, but the error I submitted above seems to be a different issue. 

I did some testing, and I THINK the issue above is caused by this:  If a frame have a face that is oriented to much sideways (example, both eyes to the right and not up + jaw to the left and not down) this error seems to come. I rotated the image counterclockwise in Windows so the face is more up/down, and then it seems to work fine.

**Comment by iperov** [comment]
error that you sent me is related to grayscale input images.

Any other errors?

**Comment by iperov** [comment]
I do not like to guess. 
If you have new error, then post steps to reproduce and attach files.

**Comment by Tesla32X** [comment]
Will do!

**Comment by iperov** [comment]
thx, fixed

**Comment by Tesla32X** [comment]
Seems to be working fine now! I appreciate it! Thx!

**Comment by iperov** [comment]
any bugs?

**Comment by Vano333** [comment]
i have its error too in CUDA10.1AVX_build_09_21 bild
Performing re-extract frames which were deleted from _debug directory.
Searching deleted files: 100%|####################################################| 2466/2466 [00:09<00:00, 252.85it/s]
Found 13 images.
Performing manual extract...
Running on GeForce RTX 2080 Ti.
Using TensorFlow backend.
 46%|######################################3                                            | 6/13 [02:31<02:56, 25.19s/it]Traceback (most recent call last):
  File "d:\FA\CUDA10.1AVX_09_21\_internal\DeepFaceLab\main.py", line 272, in <module>
    arguments.func(arguments)
  File "d:\FA\CUDA10.1AVX_09_21\_internal\DeepFaceLab\main.py", line 35, in process_extract
    'multi_gpu' : arguments.multi_gpu,
  File "d:\FA\CUDA10.1AVX_09_21\_internal\DeepFaceLab\mainscripts\Extractor.py", line 756, in main
    data = ExtractSubprocessor ([ ExtractSubprocessor.Data(filename) for filename in input_path_image_paths ], 'landmarks', image_size, face_type, debug_dir, cpu_only=cpu_only, manual=True, manual_window_size=manual_window_size).run()
  File "d:\FA\CUDA10.1AVX_09_21\_internal\DeepFaceLab\joblib\SubprocessorBase.py", line 222, in run
    self.on_result (cli.host_dict, obj['data'], obj['result'])
  File "d:\FA\CUDA10.1AVX_09_21\_internal\DeepFaceLab\mainscripts\Extractor.py", line 560, in on_result
    view_landmarks  = (np.array(self.landmarks) * self.view_scale).astype(np.int).tolist()
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'


all images is color jpeg from canon dslr.  its error (for only 13 pics) due to too large resolution and file size ?
