### ISSUE TITLE
tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: initialization error

### ISSUE THREAD

**Issue by wwdok** [iperov/DeepFaceLab#5242]
I downloaded DeepFaceLab_NVIDIA_build_01_04_2021 for windows 10, when i am runing `4) data_src faceset extract.bat`, it reported errors:
![image](https://user-images.githubusercontent.com/43233772/104342904-4ccc8980-5536-11eb-9b71-7b1c964ef9fd.png)
My env info is :
![image](https://user-images.githubusercontent.com/43233772/104343008-6a99ee80-5536-11eb-953c-80425e6f4c11.png)
Could someone give me a tip to solve it ? Thanks !

**Comment by jiteshm17** [comment]
I suggest that you use CUDA 10.1 instead of 10.2. I encountered some issues with CUDA 10.2 while using the DeepFaceLab tool
I would suggest the following
1. Uninstalling CUDA 10.2 completely and installing CUDA 10.1
2. Install CuDNN version 7.6.5 (check the installation guide [here](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-windows))
3. Reinstall Tensorflow using the command `pip install --upgrade tensorflow-gpu==2.3.0`

**Comment by wwdok** [comment]
Hi, thank you for your discussion, afterwards i found it might because the CUDA verison in `_internal\CUDA` is 11.0 that is so high that my nvidia driver can not compatible with it, so i found an older version(20200802) from [here](https://www.dfldata.xyz/forum.php?mod=viewthread&tid=150&extra=page%3D1), whose  `_internal\CUDA` is just 9.2, then i finnally can run Deepfacelab on my computer,
