### ISSUE TITLE
Identify Images in src and dst with has bad training

### ISSUE THREAD

**Issue by blanuk** [iperov/DeepFaceLab#650]
Hi there

Is there an option how to seperate some images in src and dst which has bad values in training?
i mean, if 90% is by 0.4 and the rest has spikes up to 1.0 it would be nice to sort them out and train them till de value drops down to the level of the other.

[12:04:25][#137240][2662ms]**[1.3264]**[0.5461]
[12:04:48][#137248][1400ms]**[0.6550]**[0.3033]

It would be nice if i can sort out this images and train seperate. Is that possible? like a sort by loss value?

Greetz

**Comment by TMBdf** [comment]
Is this what DFL does now? It trains more on the bad ones instead of the good ones. 

for every batch_size*16 samples,
model collects the samples with the highest error and learns them again
therefore hard samples will be trained more often

But on the other hand bad faces in src are trained more on with this, I've noticed worse results in some cases where source dataset wasn't as good as it could be (more blurry faces than necessary, similar faces from many different sources where some have worse quality). Especially with trueface.

**Comment by blanuk** [comment]
sure, but is not enought.. i have still some extreme peaks by the src... and i dont know why. so if i can sort this one out, i would be happy

**Comment by WesleyNery** [comment]
@blanuk probably because there is some bad data. A few minutes ago I found a bad face (from someone else) on my SRC after around 150k iters...it just popped up on the preview windows and i was like 'what is this doing here?!'

I guess that a feature like OP said would be a good addition

**Comment by blanuk** [comment]
yes, thats what i mean. maybe a possibility to sort them by loss value.

**Comment by wuffenberg** [comment]
faces flipped horizontally (eg in a mirror) also gives bad results

**Comment by blanuk** [comment]
well, but the question is: how to find them.
DFL knows for each file the Loss Value, so it would be helpfull to get them out in any way. i mean like sorting by loss value.

**Comment by wuffenberg** [comment]
I found a few mirrored scenes because in the training preview these faces did not converge well. But that's of course a cumbersome process which needs attention and manual work.
